version: "3"
networks:
  rina-bot:

services:
  db:
    image: "postgres"
    restart: "always"
    networks:
      rina-bot:
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  bot:
    volumes:
      - ./src:/src
    networks:
      rina-bot:
    depends_on:
      - db
    build: .
